# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 585a0612a66690785c69bfaf0c691f42a36d43023f32b856037c11a76d87bfbf13545fea0f4268019da229653204928b1ed4ece64cd3900b6be4d17d12741688

test:
  secret_key_base: be7febceb8ec59a99ce960d72accd72a95c3c0c80949f595295ecb333538262e6dd1876fcd7042977d932b347f137fbb15c1b46944e42a287cad543f056b7052

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
